import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { runCargo } from "./rust-toolchain";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const crate = resolve(root, "rust/graph-kernels");
const generated = resolve(
  root,
  "features/graph-editor/compute/kernel-asset.ts",
);
const sourceFiles = [
  "Cargo.toml",
  "rust-toolchain.toml",
  ...readdirSync(resolve(crate, "src"))
    .filter((name) => name.endsWith(".rs"))
    .sort()
    .map((name) => `src/${name}`),
];
const hash = createHash("sha256");
for (const name of sourceFiles)
  hash.update(name).update(readFileSync(resolve(crate, name)));
const sourceHash = hash.digest("hex");

if (process.argv.includes("--check")) {
  const manifest = existsSync(generated) ? readFileSync(generated, "utf8") : "";
  const asset = manifest.match(/RUST_KERNEL_URL = "([^"]+)"/)?.[1];
  if (
    !manifest.includes(sourceHash) ||
    !asset ||
    !existsSync(resolve(root, "public" + asset))
  )
    throw new Error(
      "Rust sources and checked-in Wasm differ. Run bun run build:wasm.",
    );
  const bytes = readFileSync(resolve(root, "public" + asset));
  const contentHash = createHash("sha256")
    .update(bytes)
    .digest("hex")
    .slice(0, 16);
  if (asset !== `/wasm/graph-kernels.${contentHash}.wasm`)
    throw new Error("Rust/Wasm content hash differs from its asset URL");
  if (!WebAssembly.validate(bytes)) throw new Error("Invalid checked-in Wasm");
  console.log("Rust/Wasm artifact is current");
} else {
  const result = runCargo([
    "build",
    "--manifest-path",
    resolve(crate, "Cargo.toml"),
    "--target",
    "wasm32-unknown-unknown",
    "--release",
    "--offline",
    "--locked",
  ]);
  if (result.status !== 0)
    throw new Error(
      "Rust/Wasm build failed; install Rust and the wasm32-unknown-unknown target.",
    );
  const bytes = readFileSync(
    resolve(crate, "target/wasm32-unknown-unknown/release/graph_kernels.wasm"),
  );
  const contentHash = createHash("sha256")
    .update(bytes)
    .digest("hex")
    .slice(0, 16);
  const directory = resolve(root, "public/wasm");
  mkdirSync(directory, { recursive: true });
  for (const name of readdirSync(directory))
    if (/^graph-kernels(?:\.[a-f0-9]+)?\.wasm$/.test(name))
      rmSync(resolve(directory, name));
  writeFileSync(resolve(directory, `graph-kernels.${contentHash}.wasm`), bytes);
  writeFileSync(
    generated,
    `// Generated by scripts/build-wasm.ts. Do not edit.\nexport const RUST_KERNEL_URL = "/wasm/graph-kernels.${contentHash}.wasm";\nexport const RUST_KERNEL_SOURCE_HASH =\n  "${sourceHash}";\n`,
  );
  console.log(`Rust/Wasm built: ${bytes.length} bytes`);
}
