// Generated by scripts/build-wasm.ts. Do not edit.
export const RUST_KERNEL_URL = "/wasm/graph-kernels.0a6aa1ac2de4a8aa.wasm";
export const RUST_KERNEL_SOURCE_HASH =
  "bdf3f749429edb15c57887a85d3e6dbee97493396de55e022561682af4fd59a9";
