// Generated by scripts/build-wasm.ts. Do not edit.
export const RUST_KERNEL_URL = "/wasm/graph-kernels.89d2e1ca126187d3.wasm";
export const RUST_KERNEL_SOURCE_HASH =
  "0e0fa7460fd02707ae27246e00e7ec0e292f4f28c60eebbab80f1a452660862d";
