// Generated by scripts/build-wasm.ts. Do not edit.
export const RUST_KERNEL_URL = "/wasm/graph-kernels.b0f4c21baceed2ce.wasm";
export const RUST_KERNEL_SOURCE_HASH =
  "2da801b77bf43bf6b10f227f0c7e3adaf4f7f82a3fe2fc5f265fea6de72289aa";
